apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
    name: {{ $fullname }}-service
    {{- if .Values.global.namespace }}
    namespace: {{ .Values.global.namespace }}
    {{- end }}
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      created-by: "Helm"
      application: "{{ .Values.global.application.name }}-{{ .Values.global.application.version }}"
spec:
    selector:
        app: {{ $fullname }}
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP