apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    created-by: "Helm"
    application: "{{ .Values.global.application.name }}-{{ .Values.global.application.version }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: 1
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        app: {{ $fullname }}
    spec:
      containers:
        - command: ["cloudflared"]
          args:
            [
              "tunnel",
              "--no-autoupdate",
              "run",
              "--token",
              "$(CLOUDFLARE_TUNNEL_TOKEN)",
            ]
          env:
            - name: CLOUDFLARE_TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CLOUDFLARE_TUNNEL_TOKEN
                  name: {{ $fullname }}-token
          image: cloudflare/cloudflared
          name: {{ $fullname }}-pod
      restartPolicy: Always
