 apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-admin
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.type }}
  selector:
    app: gigabit-host
    component: admin
    {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.admin.ports | toYaml | nindent 2 }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "mychart.fullname" . }}-admin
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  entryPoints: 
  {{ .Values.environmentVariables | toYaml | indent 4 }}
  routes:
  - kind: Rule
    match: {{ printf "Host(`%s`)" .Values.ingressRoute.admin.hostname }}
    services:
    - name: {{ include "mychart.fullname" . }}-admin
      port: 3000
  tls:
    certResolver: {{ .Values.ingressRoute.certResolver | quote }}
