{{- if .Values.ghcr.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr.io
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    created-by: "Helm"
    application: "{{ .Values.global.application.name }}-{{ .Values.global.application.version }}"
data:
  .dockerconfigjson: {{ .Values.ghcr.dockerconfigjson | b64enc | quote }}
{{- end }}