{{- if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "mychart.fullname" . }}-ghcr-auth
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    release: release-name
  {{- include "mychart.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
