apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-secrets
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  nautobot_token: {{ 
    required "nautobot.token is required" 
    .Values.nautobot.token | b64enc | quote }}
  postgres-supabase-url: {{ 
    required "supabase.postgresUrl is required" 
    .Values.supabase.postgresUrl | b64enc | quote 
    }}
  proxmox-token-secret: {{ 
    required "proxmox.token.secret is required" 
    .Values.proxmox.auth.token.secret | b64enc | quote 
    }}
  {{- if .Values.payments.stripe.enabled }}
  stripe-secret-key: {{ 
    required "payments.stripe.secretKey is required" 
    .Values.payments.stripe.secretKey | b64enc | quote 
    }}
  {{ end }}
  supabase-anon-key: {{ 
    required "supabase.anonKey is required" 
    .Values.supabase.anonKey| b64enc | quote 
    }}
  supabase-jwt-secret: {{ 
    required "supabase.jwtSecret is required" 
    .Values.supabase.jwtSecret | b64enc | quote 
    }}
  supabase-service-role-key: {{ 
    required "supabase.serviceRoleKey is required" 
    .Values.supabase.serviceRoleKey | b64enc | quote 
    }}
type: Opaque
