apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-secrets
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  nautobot_token: {{ required "prodSecrets.nautobotToken is required" .Values.prodSecrets.nautobotToken
    | b64enc | quote }}
  postgres-supabase-url: {{ required "prodSecrets.postgresSupabaseUrl is required"
    .Values.prodSecrets.postgresSupabaseUrl | b64enc | quote }}
  proxmox-token-secret: {{ required "prodSecrets.proxmoxTokenSecret is required"
    .Values.prodSecrets.proxmoxTokenSecret | b64enc | quote }}
  stripe-secret-key: {{ required "prodSecrets.stripeSecretKey is required" .Values.prodSecrets.stripeSecretKey
    | b64enc | quote }}
  supabase-anon-key: {{ required "prodSecrets.supabaseAnonKey is required" .Values.prodSecrets.supabaseAnonKey
    | b64enc | quote }}
  supabase-jwt-secret: {{ required "prodSecrets.supabaseJwtSecret is required" .Values.prodSecrets.supabaseJwtSecret
    | b64enc | quote }}
  supabase-service-role-key: {{ required "prodSecrets.supabaseServiceRoleKey is required"
    .Values.prodSecrets.supabaseServiceRoleKey | b64enc | quote }}
type: Opaque
