apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-web
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.type }}
  selector:
    app: gigabit-host
    component: web
    {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.web.ports | toYaml | nindent 2 }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "mychart.fullname" . }}-web
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  entryPoints:
  - websecure-int
  routes:
  - kind: Rule
    match: Host(`gigabit.host`)
    services:
    - name: web
      port: 3000
  tls:
    certResolver: andromeda-letsencrypt
