[package]
name = "provisioner"
version = "0.1.0"
edition = "2024"

[dependencies]
restate-sdk = "0.3.2"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.19"
rand = "0.9.0"
anyhow = "1.0.86"