name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # keep this if you’re checking out source
  packages: write # allow pushing to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [web, admin, worker]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          file: docker/dockerfile.${{ matrix.service }}
          push: ${{ github.ref_name == 'main' }}
          tags: |
            ghcr.io/andromedaindustries/gigabit-host/${{ matrix.service }}:${{ github.sha }}
            ${{ github.ref_name == 'main' && format('ghcr.io/andromedaindustries/gigabit-host/{0}:latest', matrix.service) || '' }}
